name: 'Depcruise PR Check'
branding:
  icon: 'file-text'
  color: 'red'
description: 'Generate depcruise report in markdown format and comment to designated PR.'
inputs:
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github).'
    required: true
  pr_number:
    description: 'Manually define the pull request number.'
  comment_includes:
    description: 'The text that should be used to find comment in case of replacement.'
    default: 'Forbidden dependency check'
  depcruise_config:
    description: 'Path to the config file for depcruise.'
    default: './.dependency-cruiser.js'
  depcruise_base_dir:
    description: 'The baseDir for depcruise to start the scanning.'
    default: 'src'
  status_check:
    description: 'If there is any rules violation detected, it will exit the job with status code.'
    default: true
runs:
  using: 'node16'
  main: 'lib/index.js'
