on: pull_request

jobs:
  test_comment_pr:
    runs-on: ubuntu-latest
    name: (NRT) Comment PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}